CREATE TABLE IF NOT EXISTS PROPRIETARIOS(
    CPF_PROP BIGINT NOT NULL PRIMARY KEY,
    CNH_PROP VARCHAR(15) NOT NULL,
    BANCO_PROP INTEGER NOT NULL,
    AGENCIA_PROP INTEGER NOT NULL,
    CONTA_PROP INTEGER NOT NULL
);