-- CREATE TABLE IF NOT EXISTS VIAGENS(
--     ID_VIAGEM BIGINT NOT NULL PRIMARY KEY,
--     CPF_PASS_VIAG BIGINT NOT NULL REFERENCES PASSAGEIROS(CPF_PASSAG),
--     CPF_MOT_VIAG BIGINT NOT NULL REFERENCES MOTORISTAS(CPF_MOTORISTA),
--     PLACA_VEIC_VIAG VARCHAR(7) NOT NULL REFERENCES VEICULOS(PLACA),
--     LOCAL_ORIG_VIAG VARCHAR(30),
--     LOCAL_DEST_VIAG VARCHAR(30),
--     DT_HORA_INICIO TIMESTAMP NOT NULL,
--     DT_HORA_FIM TIMESTAMP,
--     QTDE_PASS INT,
--     FORMA_PAGTO VARCHAR(10) NOT NULL CHECK(FORMA_PAGTO IN ('DINHEIRO', 'CARTAO', 'POSTERIORI')),
--     VALOR_PAGTO DECIMAL(10,2),
--     CANCELAM_MOT VARCHAR(1) NOT NULL CHECK(CANCELAM_MOT IN ('S', 'N')),
--     CANCELAM_PASS VARCHAR(1) NOT NULL CHECK(CANCELAM_PASS IN ('S', 'N'))
-- );
CREATE TABLE IF NOT EXISTS VIAGENS(
    ID_VIAGEM BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PASSAGEIRO BIGINT NOT NULL REFERENCES PASSAGEIROS(ID_PASSAGEIRO),
    ID_MOTORISTA BIGINT NOT NULL REFERENCES MOTORISTAS(ID_MOTORISTA),
    ID_VEICULO BIGINT NOT NULL REFERENCES VEICULOS(ID_VEICULO),
    LOCAL_ORIG_VIAG VARCHAR(30),
    LOCAL_DEST_VIAG VARCHAR(30),
    DT_HORA_INICIO TIMESTAMP NOT NULL,
    DT_HORA_FIM TIMESTAMP,
    QTDE_PASS INT,
    FORMA_PAGTO VARCHAR(10) NOT NULL CHECK(FORMA_PAGTO IN ('DINHEIRO', 'CARTAO', 'POSTERIORI')),
    VALOR_PAGTO DECIMAL(10,2),
    CANCELAM_MOT VARCHAR(1) NOT NULL CHECK(CANCELAM_MOT IN ('S', 'N')),
    CANCELAM_PASS VARCHAR(1) NOT NULL CHECK(CANCELAM_PASS IN ('S', 'N'))
    );
