CREATE TABLE IF NOT EXISTS VIAGEM(
    ID_VIAGEM BIGINT NOT NULL PRIMARY KEY,
    CPF_PASS_VIAG BIGINT NOT NULL FOREIGN KEY,
    CPF_MOT_VIAG BIGINT NOT NULL FOREIGN KEY,
    PLACA_VEIC_VIAG VARCHAR(7) NOT NULL FOREIGN KEY,
    LOCAL_ORIG_VIAG VARCHAR(30),
    LOCAL_DEST_VIAG VARCHAR(30),
    DT_HOTA_INICIO DATE NOT NULL,
    DT_HORA_FIM DATE,
    QTDE_PASS INT,
    FORMA_PAGTO VARCHAR(10) NOT NULL CHECK(FORMA_PAGTO IN ('DINHEIRO', 'CARTAO', 'POSTERIORI')),
    VALOR_PAGTO VARCHAR(10),
    CANCELAM_MOT VARCHAR(1) NOT NULL CHECK(CANCELAM_MOT IN ('S', 'N')),
    CANCELAM_PASS VARCHAR(1) NOT NULL CHECK(CANCELAM_PASS INT ('S', 'N'))
);
