-- CREATE TABLE IF NOT EXISTS MOTORISTAS_VEICULOS(
--     CPF_MOTORISTA BIGINT NOT NULL PRIMARY KEY,
--     PLACA_VEICULO VARCHAR(7) NOT NULL REFERENCES VEICULOS(PLACA)
-- );
CREATE TABLE IF NOT EXISTS MOTORISTAS_VEICULOS (
    CPF_MOTORISTA BIGINT NOT NULL,
    PLACA CHAR(7) NOT NULL REFERENCES VEICULOS(PLACA),
    PRIMARY KEY (CPF_MOTORISTA, PLACA)
    );
