-- CREATE TABLE IF NOT EXISTS MOTORISTAS_VEICULOS(
--     CPF_MOTORISTA BIGINT NOT NULL PRIMARY KEY,
--     PLACA_VEICULO VARCHAR(7) NOT NULL REFERENCES VEICULOS(PLACA)
-- );
CREATE TABLE IF NOT EXISTS MOTORISTAS_VEICULOS (
    ID_MOTORISTA_VEICULO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CPF_MOTORISTA BIGINT NOT NULL,
    ID_VEICULO BIGINT NOT NULL REFERENCES VEICULOS(ID_VEICULO),
    ID_MOTORISTA BIGINT NOT NULL REFERENCES MOTORISTAS(ID_MOTORISTA)
    );
