-- CREATE TABLE IF NOT EXISTS TIPOS_PAGTOS(
--     COD_PAGTO INTEGER NOT NULL PRIMARY KEY,
--     DESC_PAGTO VARCHAR(20)
-- );
CREATE TABLE IF NOT EXISTS TIPOS_PAGTOS (
    ID_TIPO_PAGTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COD_PAGTO INTEGER,
    DESC_PAGTO VARCHAR(20)
    );
