-- CREATE TABLE IF NOT EXISTS MOTORISTAS(
--     CPF_MOTORISTA BIGINT PRIMARY KEY NOT NULL,
--     CNH VARCHAR(15) NOT NULL,
--     BANCO_MOT INTEGER NOT NULL,
--     AGENCIA_MOT INTEGER NOT NULL,
--     CONTA_MOT INTEGER NOT NULL
-- );
CREATE TABLE IF NOT EXISTS MOTORISTAS (
    ID_MOTORISTA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CPF_MOTORISTA BIGINT NOT NULL,
    CNH VARCHAR(15) NOT NULL,
    BANCO_MOT INTEGER,
    AGENCIA_MOT INTEGER,
    CONTA_MOT INTEGER
    );
