CREATE TABLE IF NOT EXISTS MOTORISTAS(
    CPF_MOTORISTA BIGINT PRIMARY KEY NOT NULL,
    CNH VARCHAR(15) NOT NULL,
    BANCO_MOT INTEGER NOT NULL,
    AGENCIA_MOT INTEGER NOT NULL,
    CONTA_MOT INTEGER NOT NULL
);