spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cmp1611_paulo_artur_marcel
    username: postgres
    password: admin123
#    url: jdbc:postgresql://localhost:5432/cmp1611_paulo_artur

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false

springdoc:
  pathsToMatch: /**
  swagger-ui:
    use-root-path: true